[".themes/Nordic"]
  type = "git-repo"
  url = "https://github.com/EliverLara/Nordic.git"
  refreshPeriod = "48h"

[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/chosegood/kickstart.nvim"
    refreshPeriod = "8h"

[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "8h"
