import = [
  # "~/.config/alacritty/nord.toml", 
  "~/.config/alacritty/catppuccin-mocha.toml"
  "~/.config/alacritty/source_code_pro.toml"
]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "alacritty"
# TERM = "xterm-256color"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
decorations = "full"
dynamic_title = true
opacity = 0.8
